services:
  ana:
    container_name: 'ana'
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command: ["poetry", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  db:
    image: 'postgres:15'
    container_name: 'gap-postgres'
    environment:
      POSTGRES_PASSWORD: 'password'
    ports:
      - '5433:5432'
    volumes:
      - ./gap_postgres_data/:/var/lib/postgresql/data