services:
  python-dev:
    container_name: "python-dev"
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        INSTALL_NODE: ${INSTALL_NODE:-false}
    env_file:
      - ../.env
    environment:
      - GIT_EDITOR="code --wait"
    ports:
      - "8000:8000"
      - "3000:3000"
    volumes:
      - ..:/app:cached
      - ~/.ssh:/root/.ssh:ro
      - ~/.gitconfig:/root/.gitconfig:ro

  db:
    image: 'postgres:15'
    container_name: 'gap-postgres'
    environment:
      POSTGRES_PASSWORD: 'password'
    ports:
      - '5433:5432'
    volumes:
      - ..:/var/lib/postgresql/data