name: Release API

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        env:
          REGISTRY_NAME: ${{ secrets.REGISTRY_NAME }}
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
        run: |
          # Login to Docker registry
          docker login -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD $REGISTRY_NAME
          # Build Docker image
          docker build -f api/Dockerfile -t ${REGISTRY_NAME}/gap-analysis/api:latest .
          # Push Docker image
          docker push ${REGISTRY_NAME}/gap-analysis/api:latest
